### ISSUE TITLE
use Enum With values in jdl studio

### ISSUE THREAD

**Issue by abdRumman** [jhipster/jhipster-online#146]
|I am using enum with values in jdl-studio but the studio has shown me an error see the image, please !!

![image](https://user-images.githubusercontent.com/32413587/71550561-395a8900-29dc-11ea-8f38-bc8468d402ac.png)

**Comment by agaspardcilia** [comment]
It looks like the JDL Studio version used here is kinda outdated. But I'm afraid it looks like an issue of [JDL Studio](https://github.com/jhipster/jdl-studio) and not JHipster Online and is probably only a matter of JDL version. You can use the latest version of JHipster locally as a workaround.

I'm closing this since it's not the right place to post that.
