### ISSUE TITLE
Upgrade jhipster-online application to sync with generator-jhipster v6.8

### ISSUE THREAD

**Issue by vishal423** [jhipster/jhipster-online#157]
Upgrade `jhipster-online` application to leverage improvements incorporated in the main generator `v6.8`

**Comment by pascalgrimaud** [comment]
@vishal423 : why did you close the ticket ? for technical problem ? or maybe it's too much work ? In this case, I can understand, no worry.
If it can motivate, I can put a bounty on this. Just tell me

**Comment by vishal423** [comment]
@pascalgrimaud, It seems much work than I initially anticipated before creating this ticket. I will try to spend some time over the next few days/weeks, however, I don't want to commit and thus closed the ticket.

**Comment by SudharakaP** [comment]
@vishal423 : Would you mind if I give it a try at this issue? I have ample time and can do it in the next week or so. :smile:

**Comment by vishal423** [comment]
@SudharakaP, sure.

**Comment by SudharakaP** [comment]
> @SudharakaP, sure.

Thanks. :+1:

**Comment by SudharakaP** [comment]
I've created a draft pull request to upgrade this to v6.8.0. I've managed to resolve the merge conflicts (to the best of my knowledge) and have it compile, build and start up correctly. 

But most of the front-end functionality is broken I think especially due to heavy upgrades to Angular. Any help will be greatly appreciated. :pray: 

I'll give it another try in a couple of days. :thinking:

**Comment by pascalgrimaud** [comment]
cc @agaspardcilia @chrisdns @wmarques 
It would be really appreciated if we can get help from you

**Comment by wmarques** [comment]
I'll have a look on friday

**Comment by agaspardcilia** [comment]
I have a bunch of spare time these days, I'm gonna give it a look.

**Comment by agaspardcilia** [comment]
@SudharakaP Do you have a list of stuff not working or something like that? I'm currently doing one.

**Comment by agaspardcilia** [comment]
Right below are the first things I noticed while trying to use the application:

### Misc

- [ ] Login alert not working
- [ ] Liquibase data script not being loaded (might be a local issue altough it works on the current master)
- [ ] Weird default icon color
- [ ] Home is not being switched to authenticated state
- [ ] Authentication is broken (gotta use the account service instead of the principal service to check authentication status)
- [ ] NavBar is broken
- [ ] `ng.probe is not a function` popping in console
- [ ] Jdl Studio has been removed
- [ ] Application generation/download refreshes the page at the end of the generation

### Registration
- [ ] Is broken, looks like there's something wrong in backend 
- [ ] Invalid format error message for mail input is not working

### User management
- [ ] Pretty much every actions are broken

### Admin pages
- [ ] Router configuration seems to be broken, can't access any pages other than user management

### Settings
- [ ] Accound deletion modal is not working

### Statistics
- [ ] Backend error when trying to display some data

## Unable to test
- [ ] Account activation
- [ ] Password reset
- [ ] Design entities

There's a lot of broken stuff as you can see. This is going to be quiet a bit of work. I think most of it can be fixed quiet easily but I'm kinda rusted Angular wise, so it's going to take a bit of time.

**Comment by pascalgrimaud** [comment]
@SudharakaP : can you tell us how you upgrade ? using `jhipster upgrade` or manually ?

**Comment by SudharakaP** [comment]
@agaspardcilia : Thanks for summarizing it. Yes most of this seems broken; which makes me think if we should do the upgrade again from the beginning instead of trying to fix this so that maybe you'll have better chance and resolving the merge conflicts probably better than I did. :smile: 

@pascalgrimaud : I used `jhipster upgrade`; and I resolved the conflicts simply by not trying to remove any code that we added. But now I think probably a better approach might be to upgrade this by steps rather than trying to upgrade the whole thing to v6.8.0 in one go? :thinking: :thinking:

**Comment by pascalgrimaud** [comment]
from my personal experience, I never manage to use this sub generator... always broken from my side

**Comment by agaspardcilia** [comment]
@SudharakaP Indeed, the Angular upgrade has really been messed up by the whole upgrade. I'll give it a try to see if I can get a better result.

@pascalgrimaud Me too, last time we upgraded jhonline, we didn't used it iirc.

**Comment by SudharakaP** [comment]
> from my personal experience, I never manage to use this sub generator... always broken from my side

Oh no... :cry: then we shouldn't use my PR, since I used that subgenerator thinking that it would be fine.

**Comment by pascalgrimaud** [comment]
That's the reason why @vishal423 closed the ticket initially.
Indeed, it's a lot of work to upgrade properly this project with all last libraries for front and back...
I would be easier if we coded it, using side-by-side approach, but it's another story.

Then, I'm not sure it will deserve to spend so much time on this, as our users won't see a lot of difference at https://start.jhipster.tech/#/

**Comment by wmarques** [comment]
Agree on that... It would be better to do only a library upgrade on front end, that will be enough I think.

**Comment by vishal423** [comment]
If no one is looking into the upgrade, I can try to spend some time over the next few days. However, as I said before, I don't want to commit upfront as progress would largely depend on available bandwidth.

**Comment by SudharakaP** [comment]
@vishal423 : Sure thanks. I can help too if you'd like to; maybe if you can do part of it I can try to do the other half. Can take a look next week; need some break from the upgrade lol. :smile:

**Comment by pascalgrimaud** [comment]
I'm changing the bounty here as it was so much work here, and it will be well deserved
