### ISSUE TITLE
Unable to create new account

### ISSUE THREAD

**Issue by infomaven** [jhipster/jhipster-online#18]
I used the site to create a new account from scratch.
- When I tried to log in, my password was rejected
- When I used password recovery link I got an error saying my "email not registered"
- When I tried to create a new user account to register the email, I got an error saying "email and username already taken"

This seems to be an endless loop of frustration.   :(

**Comment by jdubois** [comment]
I'll have a look - can you tell me the username you used? Or when you
registered ?

Le 21 sept. 2017 8:00 AM, "Nadine Whitfield" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
OK I found you :-)
I had no idea we had so many people registering!!

**Comment by jdubois** [comment]
- In my logs you did receive an email to activate your account, but as it's not activated, I guess you didn't see it
- As your account is not activated, you can't log in (so that explains your first point)
- I'm not sure about your second point, but if the account isn't activated, I'm not sure you can recover your password ->this is the "standard" JHipster workflow, and to be honest I don't remember how this works (I would need to check our code..).
- And of course you can't register, as you already have an account waiting to be activated (this is your 3rd point)

Then:
- Of course I activated your account manually, so now it should work :-)
- Otherwise, after 2 days non-activated accounts are deleted (standard JHipster workflow), so that would be solved at some point

-> thanks because you make me realize the JHipster workflows are not fully documented (those should be explained on our website), so there's definitely something to improve here

I'm closing this as I activated manually your account, so it should work, but please comment if you have any more issue

**Comment by infomaven** [comment]
Thanks for following up.

I ventured into my junk mail folder, and sure enough, there was an email from my registration on Tue.

Thank you for activating my account.

 I would hate for someone else to claim that username :)

Nadine

Sent from my iPhone

On Sep 21, 2017, at 12:29 AM, Julien Dubois <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #18<https://github.com/jhipster/jhipster-online/issues/18>.
