### ISSUE TITLE
Unable to reset my password

### ISSUE THREAD

**Issue by woybgroup** [jhipster/jhipster-online#281]
Link :- https://start.jhipster.tech/
Forgot Password not working.
After entering email id woybgroup@gmail.com... get the message email sent. But I dont get any email.

**Comment by SudharakaP** [comment]
@woybgroup : Thanks for reporting the issue; we are looking into it. 😄

**Comment by jdubois** [comment]
Thanks a lot, I just had a look at the logs:

- It has been working fine until 3 days ago (we always have several people resetting their password)
- There's been no logs for three days, and I couldn't receive an email with my own password -> so there's something buggy on their side since 3 days

@SudharakaP I've already seen this in the past, and I just rebooted the server and it worked. I believe there's some issue on the Mailgun side and restarting everything solves it -> could you restart the server and check it? You need to click on "forgotten password" and you should get an email

**Comment by SudharakaP** [comment]
> Thanks a lot, I just had a look at the logs:
> 
>     * It has been working fine until 3 days ago (we always have several people resetting their password)
> 
>     * There's been no logs for three days, and I couldn't receive an email with my own password -> so there's something buggy on their side since 3 days
> 
> 
> @SudharakaP I've already seen this in the past, and I just rebooted the server and it worked. I believe there's some issue on the Mailgun side and restarting everything solves it -> could you restart the server and check it? You need to click on "forgotten password" and you should get an email

@jdubois : I just restarted and now it seems to work. Thank you. 😄

**Comment by SudharakaP** [comment]
This seems to be a MailGun issue and there's nothing wrong with the jhipster-online service. So I am closing this for now but if this occurs again we will look into it more on what could be done. 🤔
