### ISSUE TITLE
Configurator and propagation choices

### ISSUE THREAD

**Issue by FAMILIAR-project** [jhipster/jhipster-online#32]
Hi, 

It is not really an issue, but an open question driven by curiosity ;) 
The website is fantastic and the configurator seems nicely implemented. 
In particular, at each selection by a user, there is a "propagation" to other choices, forcing other values (with implications/exclusions)  

I am wondering how it is implemented: do you rely on facilities offered by Inquirer https://github.com/SBoudrias/Inquirer.js/ ? 
Or have you implemented an ad-hoc solution? 

Best regards, 

Mathieu Acher

**Comment by jdubois** [comment]
You're going to be disappointed: this is hand-coded! I "know" what to
propagate, and I also copy stuff from the generator. So nothing very smart
here!!

Le 21 févr. 2018 17:32, "FAMILIAR project" <notifications@github.com> a
écrit :

Hi,

It is not really an issue, but an open question driven by curiosity ;)
The website is fantastic and the configurator seems nicely implemented.
In particular, at each selection by a user, there is a "propagation" to
other choices, forcing other values (with implications/exclusions)

I am wondering how it is implemented: do you rely on facilities offered by
Inquirer https://github.com/SBoudrias/Inquirer.js/ ?
Or have you implemented an ad-hoc solution?

Best regards,

Mathieu Acher

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/jhipster-online/issues/32>, or mute the thread

**Comment by jdubois** [comment]
In fact it can be wrong in some places, the only "correct" workflow is the one from the generator - too bad it can't be easily used, I know it would be useful for your work @FAMILIAR-project
