### ISSUE TITLE
JDL Studio Inaccessible

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-online#34]
https://start.jhipster.tech/jdl-studio/ is not working, it appears to be looking for `index.html.htm` instead of `index.html`. 

It does work if you specify index.html like https://start.jhipster.tech/jdl-studio/index.html
```
Status: Internal Server Error (Internal Server Error)
Message: Request processing failed; nested exception is
org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/jdl-studio/index.html.htm",
template might not exist or might not be accessible by any of the configured Template Resolvers
```

**Comment by jdubois** [comment]
Thanks @ruddell - I just restarted the server, and it's working again.

It is the second time this happens, so it's not very often, but still that's worrying:

- It looks like after "some time" Thymeleaf crashes. And that would be a Thymeleaf bug, so that could be quite annoying for us.
- As it already happened once, I was monitoring this page with a Google Cloud Healthcheck, which runs every 5 minutes (and on several geographic areas), and it totally missed the issue!! So maybe our "Internal Server Error" message wasn't replying with a 500 status code - there's no way to know, now that I restarted the server!! As this is also the standard JHipster error page, I also need to check that.

Of course, that page is just static, I shouldn't even serve it with Thymeleaf - but it looks like this could help find a couple of issues in JHipster, so let's keep it that way for the moment.
