### ISSUE TITLE
Production crash on https://start.jhipster.tech/jdl-studio/

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-online#37]
The Web page on https://start.jhipster.tech/jdl-studio/ crashes from time to time:

- This has already happened 3 times
- This doesn't seem correlated with anything else: I guess there's one user who triggers the bug, but I have no idea how he does that

I'm doing this ticket mainly for @danielfernandez as I believe this is an interesting Thymeleaf issue, but for us this should be solved in the future.

Here is what happens:

- The page at https://start.jhipster.tech/jdl-studio/ can work for several weeks without any problem
- Suddenly, it gets the following error: `Caused by: org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/jdl-studio/index.html.htm", template might not exist or might not be accessible by any of the configured Template Resolvers`
- Then the page always shows the JHipster error page

What is strange is that it gets broken suddenly, and it tries to load a template which has the wrong suffix (`/index.html.htm"`), instead of the normal `index.html` page. 

This issue should be solved in the future as:

- This is a static page and shouldn't be served using Thymeleaf
- Thymeleaf code is refactored in JHipster 5

**Comment by danielfernandez** [comment]
Thanks. Thymeleaf has no reason to automatically add a `.htm` suffix to any template resolution operations unless specified so, and from #34 I see that while this is failing the `/index.html` still works. So my first approach would be to think that maybe there is a proxy or a web filter that somehow starts resolving `/` into `/index.html.htm` instead of `/index.html`. Could that be a possibility?

Alternatively, could you please specify which template resolver(s) are you using, whether they set the `setSuffix(...)` and `setForceSuffix(...)` properties and, in affirmative case, to what values? Also, are there any template `aliases` being set?

More questions: when `/` is being accessed in your application, how is Thymeleaf called? if this is a Spring MVC controller, what is the exact view name value returned by this controller? if not, is Thymeleaf's `TemplateEngine#process(...)` method called directly, and with what `template` value?

**Comment by jdubois** [comment]
Thanks @danielfernandez !
This is on a modified JHipster 4 version:

- Thymeleaf 2.1.5
- Configured using Spring Boot 1.5.6

The Web page is in `src/main/resources/static/jdl-studio` which is the standard Spring Boot directory for static assets.

And as I didn't want this page to be loaded by Thymeleaf (it's standard HTML), I did in my Spring Boot config:

```
    thymeleaf:
        mode: XHTML
        excluded-view-names: /jdl-studio/index.html
```

**Comment by danielfernandez** [comment]
Thanks. So I assume you are using the default autoconfiguration for Thymeleaf 2.1 in Spring Boot 1.5. If I'm right, this means that Thymeleaf has no reason to be resolving or trying to process static resources in `src/main/resources/static` unless your boot configuration specifically says so, as Spring Boot places Thymeleaf templates in `src/main/resources/templates` and adds this folder as a `prefix` to the Spring-resource-based resolver configured into the Thymeleaf engine.

Also, if I understand correctly the scenario it seems that  if somebody inputs a `/index.html.htm` URL at the browser in your application, this ends up being transformed into Thymeleaf trying to parse a `/src/main/resources/templates/jdl-studio/index.html.htm` template, am I right? If so, and given Thymeleaf does not manage the controller layer, am I right in supposing that you have some kind of default controller that redirects every unmapped URL to a Thymeleaf template with the same name?

The default Thymeleaf autoconfiguration in Spring Boot does not automatically add any `.htm` suffix to template names, and the same is true for any involved Thymeleaf behaviours. Also, being something that once it happens doesn't stop happening, it does look as some kind of wrongly updated cache, but Thymeleaf's template cache contains the objectual model of parsed templates, so at first though I would say there is no way for Thymeleaf to repeatedly wrongly resolve a template that it hasn't been able to read and parse (it would have never been put into the cache).

I'm still seeing the proxy-or-web-filter caching the resolution of `/` as `/index.html.htm` as a quite feasible possibility from my standpoint. Does your application or your deployment include any components that might have such behaviour?

**Comment by danielfernandez** [comment]
OK, this is an interaction between the `ThymeleafViewResolver` and Spring Boot 1.5's `ContentNegotiatingViewResolver`, which calls the former and at some point is *learning* that `.htm` is a valid suffix for view names corresponding to requests that have expected media type of `text/html`, and since that moment on is always forcing Thymeleaf to resolve a `/jsl-studio/index.html.htm` template after Thymeleaf denies the resolution of `/jsl-studio/index.html` (see [the code](https://github.com/spring-projects/spring-framework/blob/v4.3.16.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/view/ContentNegotiatingViewResolver.java#L294-L318)). The `.html`  one is excluded at the Thymeleaf side, but the `.html.htm` isn't... so it fails because such template doesn't exist.

I will need to dive a bit deeper into how this mechanism is working and how `.htm` is an issue and the `.html` suffix doesn't appear to be before determining if there is anything that can be done from the Thymeleaf side to avoid this kind of situation. Anyway, the first thing that strikes me is that `ContentNegotiationViewResolver` seems to prefer a non-exact-match `index.html.htm` resolution from Thymeleaf than an exact-match `index.html` resolution from `InternalResourceViewResolver`. I understand view resolver ordering applies here, but maybe without an exact match it would make sense for the mechanism to be more lenient.

Anyway, as said I would need to understand this a bit better first.

**Comment by danielfernandez** [comment]
So, this only happens in Spring Boot 1.5.x, not in Spring Boot 2.0.x. 

First, some preliminary context on view resolution and content negotiation (valid both for Spring Boot 1.5.6 and 2.0.1):

  * **I**. View resolution in Spring Boot is based on a `ContentNegotiatingViewResolver`, which internally queries a sequence of `ViewResolver` instances. In this case, the important ones are `ThymeleafViewResolver` and `InternalResourceViewResolver`, which are queried in this order.
  * **II**. Resolution at `ContentNegotiatingViewResolver` works such that for each resolution, all view resolvers in the sequence are queried and their returned results are set into a list of *candidate views*. Such querying is performed like this for each `ViewResolver` in the sequence
     * **II.1**. First, the `ViewResolver` is [asked to resolve the exact view name](https://github.com/spring-projects/spring-framework/blob/v4.3.16.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/view/ContentNegotiatingViewResolver.java#L299) (e.g. `/jdl-studio/index.html`).
     * **II.2**. Then, if the *requested media types* (`Accept` HTTP header in the request) have any associated file extensions in the `ContentNegotiationManager`, then the `ViewResolver` is [also asked to resolve the view name with each of those extensions suffixed](https://github.com/spring-projects/spring-framework/blob/v4.3.16.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/view/ContentNegotiatingViewResolver.java#L305-L311) (e.g. `/jdl-studio/index.html.html`, `/jdl-studio/index.html.htm`, `/jdl-studio/index.html.jsp`, etc.)
  * **III**. Out of that list of *candidate views*, the first view which is a redirect or, alternatively, which *content type* matches any of the *requested media types* (`Accept` HTTP header), [will be considered *best view* and executed](https://github.com/spring-projects/spring-framework/blob/v4.3.16.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/view/ContentNegotiatingViewResolver.java#L320-L348).
  * **IV**. By default in both Spring Boot 1.5.6 and 2.0.1, the `text/html` media type has *no extensions* associated at application startup time. So by default view resolvers are asked to resolve only the original *view name* in both versions of Spring Boot, for typical HTML requests made from a browser (i.e. at application startup time, only step **II.1** above does apply).
  * **V**. Also note that `ThymeleafViewResolver`, in absence of a value for its `viewNames` configuration property, does affirmatively resolve any view names that are not included in the *exclusion list* (`excludedViewNames` configuration property), independently of whether a template file for that view name actually exists or not. Effective template existence is checked in a later step because Thymeleaf's template resolution mechanism is very generic and, for a start, templates don't even have to be based on *files* at all. So the inclusion (`viewNames`) and exclusion (`excludedViewNames`) lists are the only sources of truth to determine if the view resolver will consider a view name *resolvable* or not. Admittedly, though, this template resolution mechanism should probably need to be somehow extracted to a separate (previous) step in Thymeleaf 3.1 to avoid this situation.

Now, once the context is established, this is the sequence that causes this issue in Spring Boot 1.5.6:

  * **1**. The first time the `jdlstudio()` controller method executes, it asks Spring MVC (4.3.16) for the resolution of `/jdl-studio/index.html`. The template resolution mechanism explained above asks `ThymeleafViewResolver`, this tells `ContentNegotiatingViewResolver` that it cannot resolve that (because it is *excluded*), and then given there are **no extensions** registered at `ContentNegotiationManager` for the `text/html` media type, no more questions are asked to `ThymeleafViewResolver` (no step **II.2** this time). Then `InternalResourceViewResolver` kicks in and resolves that view name as an *internal resource*. We will see now what that actually means.
  * **2**. The `View` instance returned by `InternalResourceViewResolver` is an `InternalResourceView` instance for the `/jdl-studio/index.html` resource. When Spring MVC asks this instance to render itself, the `InternalResourceView` object does so by getting the `javax.servlet.RequestDispatcher` and asking it to **forward** to that `/jdl-studio/index.html` resource. This operation actually *executes* that resource as it it were a `.jsp` file, starting the whole process as if called from the browser URL: applies all the filters, tries to find a handler, etc.
  * **3**. The first time this happens the end result is fine, but in the process of finding a handler for the `/jdl-studio/index.html` request internally generated by `InternalResourceView`, one of the possible matching handlers tested is obviously `RequestMappingHandlerMapping` (the same mapping responsible for assigning `@Controller` methods to requests). The `RequestMappingHandlerMapping` ends up answering that it cannot handle the request for `/jdl-studio/index.html` because it doesn't match the request mapping of any of the application's controller methods, but in the process of trying to match it leaves an **undesirable (in this case) side effect**. The reasons for this *side effect* need to be also explained in steps:
     * **3.1**. At least one of the mappings configured in `RequestMappingHandlerMapping` for every Spring Boot 1.5 application is a mapping for the `/error` path with *produced media type* of `text/html`. The `RequestMappingInfo` for this mapping tries to match the internal `/jdl-studio/index.html` *forward* request with itself and obviously fails because the path does not match but, during this process, the part of its matching mechanism that tries to match the *produced media type* (`text/html`) –modelled as a `ProducesRequestCondition` object– does indeed match, because the internal `/jdl-studio/index.html` request does specify `text/html` as its *requested media type*.
     * **3.2**. So how can this positive (but partial) match of media types between an `/error` mapping and an internally dispatched *forward* for `/jdl-studio/index.html` be an issue? because [`ProducesRequestCondition#getAcceptedMediaTypes(request)`](https://github.com/spring-projects/spring-framework/blob/v4.3.16.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/condition/ProducesRequestCondition.java#L263-L266) ends up calling [`ContentNegotiationManager#resolveMediaTypes(request)`](https://github.com/spring-projects/spring-framework/blob/v4.3.16.RELEASE/spring-web/src/main/java/org/springframework/web/accept/ContentNegotiationManager.java#L123-L132), and this latter method goes through all of its configured `ContentNegotiationStrategy` instances trying to resolve the media types that could be associated to the examined request (`/jdl-studio/index.html`, in this case).
     * **3.3**. And how is this an issue? Because [one of the `ContentNegotiationStrategy` configured at the `ContentNegotiationManager`](https://github.com/spring-projects/spring-framework/blob/v4.3.16.RELEASE/spring-web/src/main/java/org/springframework/web/accept/ContentNegotiationManagerFactoryBean.java#L255-L268) is a `ServletPathExtensionContentNegotiationStrategy`, which, when queried, not only considers that the fact that the request path (`/jdl-studio/index.html`) ends in `.html` is enough to determine that the expected media type for this request should be `text/html`, but [also **caches this `.html` extension**](https://github.com/spring-projects/spring-framework/blob/v4.3.16.RELEASE/spring-web/src/main/java/org/springframework/web/accept/AbstractMappingContentNegotiationStrategy.java#L78-L82) as a valid extension for `text/html` at the `ContentNegotiationManager` mentioned in point **II.2** of the overall context explained above, effectively enabling the **II.2** mechanism for any subsequent requests.
  * **4**. So this first request works OK, but it leaves a side effect that makes that, according to step **II.2**, for each internal *forward* request generated from that on to `/jdl-studio/index.html`, all configured `ViewResolver` will not only be asked to resolve `/jdl-studio/index.html`, but also `/jdl-studio/index.html.html`. And given `ThymeleafViewResolver` has no exclusion configured for that, it will answer *"yes, I can resolve that"*, and then be selected as *best view*, executed and... *fail*.

There are still things I cannot understand here, as for example why this doesn't happen to you *much more often*. I guess it should have to do with the fact that only the `.htm` suffix is triggering this failure sequence for you and not `.html`, but not knowing the code I'm failing to understand why. Might have something to do with your error mappings (maybe you don't have the one that causes this sequence but a different one that is only triggered when a `.htm` URL is requested... anyway, whatever the specific circumstances of your application, I'm pretty sure the overall failure sequence explained above is the reason of your problems.

So: **why does this *not* happen in Spring Boot 2.0?** Because in Spring Boot 2.0, path-extension-based content negotiation is disabled by default. You need to explicitly state that you want it in order for it to apply. In fact the [`ContentNegotiationManagerFactoryBean` class in spring-web 5.0.4 contains this note](https://github.com/spring-projects/spring-framework/blob/v5.0.4.RELEASE/spring-web/src/main/java/org/springframework/web/accept/ContentNegotiationManagerFactoryBean.java#L81-L86):

```
 * <strong>Note:</strong> if you must use URL-based content type resolution,
 * the use of a query parameter is simpler and preferable to the use of a path
 * extension since the latter can cause issues with URI variables, path
 * parameters, and URI decoding. Consider setting {@link #setFavorPathExtension}
 * to {@literal false} or otherwise set the strategies to use explicitly via
 * {@link #setStrategies(List)}.
```

And... **how to solve this?** Well, I'm not sure, to be honest 🙂. At first evaluation, I would resist to call this a *bug* either on the Thymeleaf side or on the Spring Boot side. It's more of a *very unfortunate interaction*. It would definitely be better if `ThymeleafViewResolver` didn't consider everything not explicitly excluded as *resolvable*, but that is not possible nowadays, and I cannot see how the Thymeleaf side can do anything in scenarios like these to avoid being asked for `/jdl-studio/index.html.html` or `/jdl-studio/index.html.htm`. It is true that Spring Boot 2.0 users would be fine, but they would only be so as far as they don't enable path-extension-based media type resolution, which they can do even if it now seems to be clearly recommended-against.

A possible option here would be that Spring's `ViewResolver` implementations could *opt-out* of content-negotiation-extension-based resolution attempts at the `ContentNegotiationViewResolver` (i.e. opt-out of the **II.2** step), so that specific view resolvers like Thymeleaf could explictly request not to be queried for these additional resolutions, which IMHO don't make much sense from the Thymeleaf standpoint...

Again, I'll have to think a bit more about possibilities, and maybe talk to the Spring Boot people about this.

As a workaround for your specific application (and only for Spring Boot 1.5.x), I would override the `configureContentNegotiation(configurer)` method in `WebMvcConfigurerAdapter` (which is meant precisely to fine-tune this mechanism) and set `favorPathExtension(false)` to disable path-extension-based media type resolution (assuming you don't actually need it):

```java
@Configuration
public class MyAppWebMvcConfiguration extends WebMvcConfigurerAdapter {

    ...

    @Override
    public void configureContentNegotiation(final ContentNegotiationConfigurer configurer) {
        super.configureContentNegotiation(configurer);
        configurer.favorPathExtension(false);
    }

    ...

}
```

Hope this helps.

**Comment by jdubois** [comment]
Thank you so much @danielfernandez !!!
As I said on Twitter at https://twitter.com/java_hipster/status/984156645344337926 I have found the issue thanks to you!
I'll correct this tomorrow - sorry I'm not posting details here, or anyone will be able to easily crash the application :-)
So I'll give them once it's corrected!

**Comment by jdubois** [comment]
The server is updated, no crash anymore :-)

@danielfernandez was of course right, it's an issue with Spring Boot's `ContentNegotiatingViewResolver` which indeed "learned" to use Thymeleaf for the https://start.jhipster.tech/jdl-studio/ URL.

- To make the server crash, you needed to use an "*.htm" URL inside the /jdl-studio/ directory (no problem in the other directories!)
- As we get hack attempts all the time (you have no idea the number of attacks we get, really), some attacker was trying all possible URL, including https://start.jhipster.tech/jdl-studio/index.html.htm (no idea why!). This made Thymeleaf "learn" about that URL, as @danielfernandez explained.
- So once this URL was called, Thymeleaf was always trying to serve the content, and that was failing.

The solution was simply to use `excluded-view-names: /jdl-studio/*` instead of `excluded-view-names: /jdl-studio/index.html` in the Spring Boot configuration. Now Thymeleaf is clearly excluded, and no problem anymore.

Thanks so much to @danielfernandez !
