### ISSUE TITLE
No email received when creating an account on jhipster online

### ISSUE THREAD

**Issue by regisduflo** [jhipster/jhipster-online#78]
No email received when creating an account on jhispter online
Tried to create 4 differents accounts but nothing received for activationg my account and so unable to sign-in on registered....

**Comment by jdubois** [comment]
Let me check, thanks!

**Comment by jdubois** [comment]
Oh, it looks like outlook.com and hotmail.com (I saw both your emails in the logs) are blocking our mail provider (Mailgun).
For the record, here is the error message:

```
JHipster Online account activation' Server response: 550 5.7.1 Unfortunately, messages from [209.61.151.224] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [DM3NAM03FT022.eop-NAM03.prod.protection.outlook.com
```

@regisduflo I'm activating your account manually (the first one you created, `neptuneo`). I hope this is temporary, otherwise please contact me if you lose your password!

**Comment by regisduflo** [comment]
Thanks a lot

**Comment by regisduflo** [comment]
i'm able to connect with neptuneo thanks again

**Comment by jdubois** [comment]
Great, thanks a lot!

**Comment by jdubois** [comment]
If anyone reads this and has the same issue: please create a new ticket and I'll manually activate your account, too!
