### ISSUE TITLE
BitBucket configuration

### ISSUE THREAD

**Issue by M-Fararjeh** [jhipster/jhipster-online#91]
Hello all,

Please can you tell me If I can connect JDL to private BitBucket instance ? I need to apply entities  on the project using JDL.

**Comment by chrisdns** [comment]
Hi,

At the moment JHipster Online only provides GitHub and GitLab as Git providers, but to achieve what you want you can still create a JDL file using the [JDL Studio](https://start.jhipster.tech/jdl-studio/) and import it into your project with `jhipster import-jdl <your_jdl_file>`

**Comment by jdubois** [comment]
Yes, sorry but BitBucket integration isn't done (not even planned!).

**Comment by atomfrede** [comment]
@M-Fararjeh Of course contributions welcome. Gitlab support was added that way too.

**Comment by M-Fararjeh** [comment]
Thanks for replying, I wish to add this feature to the roadmap.

**Comment by jdubois** [comment]
Awesome !
@M-Fararjeh it's probably not very hard if Bitbucket has a good Java library which can create projects, add contributors, do a PR... We are not doing something very complex, but you need the API to do this.

In order to have something  clean: could you create a specific ticket for this, to detail your work on this? I know some other people who might also be interested, I'll ask them if they want to join forces with you.
