### ISSUE TITLE
Issue creating entity using online JDL studio

### ISSUE THREAD

**Issue by zargerubaid** [jhipster/jhipster-online#98]
While creating entity for my project using JDL, i am not able to see the the graphical design and relationships between the entities.

Only default image is coming.

**Comment by pascalgrimaud** [comment]
Hard to know what you did. 
You need to provide more details, which screen, which url etc.

**Comment by zargerubaid** [comment]
I am using this url :  https://start.jhipster.tech/jdl-studio/
[TravelTool.txt](https://github.com/jhipster/jhipster-online/files/2839737/TravelTool.txt)

These are going to by entities.

**Comment by pascalgrimaud** [comment]
I suggest you to use VSCode with JHipster Plugin.
See https://www.jhipster.tech/jhipster-ide/

You'll see there are some errors in your JDL, like:
- Field name should start with a lower case
- REQUIRED in uppercase, instead of lowercase
- additional `,` at the end of the last entities
etc

That's why you didn't see anything.
I'm closing this, as it's not a JHipster Online bug.
